[[bin]]
name = 'bitwise-and-of-numbers-range'
path = 'src/0201.bitwise-and-of-numbers-range/solution.rs'

[[bin]]
name = 'missing-number'
path = 'src/0268.missing-number/solution.rs'

[[bin]]
name = 'cheapest-flights-within-k-stops'
path = 'src/0787.cheapest-flights-within-k-stops/solution.rs'

[[bin]]
name = 'find-the-town-judge'
path = 'src/0997.find-the-town-judge/solution.rs'

[dependencies]
anyhow = '1.0.80'
leetgo-rs = '0.2.1'
serde = '1.0.197'
serde_json = '1.0.114'

[package]
edition = '2021'
name = 'leetcode-solutions'
version = '0.1.0'
